name: fastapi_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - pip:
      - fastapi
      - uvicorn
      - transformers
      - pandas
      - requests
      - torch
